# Generated by Django 5.1.4 on 2025-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload picture', null=True, upload_to='doctors/pictures/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
